[package]
name = "code2pdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
glib = "0.15"
gtk4 = { version = "0.9.6", package = "gtk4", features = ["v4_12"] }
gio = "0.20"

[build-dependencies]
glib-build-tools = "0.18"

[package.metadata]
gschema = "schemas/com.github.username.sebastiandanconia.code2pdf.gschema.xml"
